Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -39,8 +39,17 @@ jobs:
     runs-on: ubuntu-latest
     environment: development
     steps:
+      - name: Validate if we are running a tag
+        run: |
+          if [[ "${ GITHUB_REF} " != refs/tags/* ]]; then
+            echo "We need a tag to ensure we are deploying working services. Aborting workflow..."
+            exit 1
+          fi
       - name: Set IMAGE_TAG
-        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/tags/} | sed -E 's/backoffice\/(.*)/\1/')" >> $GITHUB_ENV
+        run: |
+          TAG_NAME=${ GITHUB_REF#refs/tags/ }
+          IMAGE_TAG=$(echo $TAG_NAME) | sed -E 's/backoffice\/(.*)/\1/')
+          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
       - run: echo ${{ env.IMAGE_TAG }}
       - run: "echo dev"
           
